spring:
  application:
    name: webIde
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://db:3308/als_ide_db?useSSL=false&serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/docker_root?
    username: root
    password: "!als1234"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
        show-sql: true
    hibernate:
      ddl-auto: update  # Change this as needed (create-drop, update)

jwt:
  secret: b298ce3826d81f25acf1f1aa631637ae21422dd8c1bbc99e50d4d827f7b5bd1350de995baa0ee13255f37d2b39c9d2db4f1b618cc299c8052e6ec7a1c15c1944